### Use 'Top 12 Forecast Probability' to analysis performance for each season

### Use 'Top 12 Forecast Probability' and then select the top 2 highest probability.

In [13]:
Accuracy(master_df,forecast_df)

,season,top_n,success,Hit rate,18,17,19,16,13,14,10,12,20,performance
0,2016-2017,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
1,2016-2017,3,3,1.00,"1/1,57","2/2,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",85.666667
2,2016-2017,5,5,1.00,"2/2,61","3/3,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",84.400000
3,2016-2017,10,10,1.00,"3/3,40","6/6,100","0/0,0","0/0,0","1/1,48","0/0,0","0/0,0","0/0,0","0/0,0",76.800000
4,2016-2017,20,20,1.00,"4/4,45","11/11,100","1/1,0","3/3,0","1/1,48","0/0,0","0/0,0","0/0,0","0/0,0",66.400000
5,2017-2018,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
6,2017-2018,3,3,1.00,"0/0,0","3/3,99","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",99.000000
7,2017-2018,5,5,1.00,"2/2,94","3/3,99","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",97.000000
8,2017-2018,10,10,1.00,"6/6,93","3/3,99","1/1,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",85.500000
9,2017-2018,20,19,0.95,"10/10,93","6/6,99","2/2,50","0/0,0","1/1,0","0/1,0","0/0,0","0/0,0","0/0,0",81.200000
10,2018-2019,1,1,1.00,"1/1,70","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",70.000000
11,2018-2019,3,3,1.00,"1/1,70","0/0,0","1/1,0","1/1,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",23.333333
12,2018-2019,5,5,1.00,"1/1,70","2/2,100","1/1,0","1/1,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",54.000000
13,2018-2019,10,10,1.00,"3/3,85","3/3,100","2/2,0","1/1,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",55.500000
14,2018-2019,20,20,1.00,"4/4,88","8/8,100","2/2,0","2/2,0","0/0,0","0/0,0","1/1,0","1/1,0","2/2,0",57.600000
15,2019-2020,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
16,2019-2020,3,3,1.00,"1/1,92","2/2,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",97.333333
17,2019-2020,5,5,1.00,"2/2,72","2/2,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",68.800000
18,2019-2020,10,10,1.00,"4/4,77","5/5,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",80.800000
19,2019-2020,20,20,1.00,"10/10,79","8/8,100","0/0,0","0/0,0","1/1,0","0/0,0","0/0,0","1/1,0","0/0,0",79.500000

### Use 'Top 12 Forecast Probability' and then select the top 3 highest probability.

In [9]:
Accuracy(master_df,forecast_df)

,season,top_n,success,Hit rate,18,17,19,16,13,14,10,12,20,performance
0,2016-2017,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
1,2016-2017,3,3,1.00,"1/1,44","2/2,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",81.333333
2,2016-2017,5,5,1.00,"2/2,46","3/3,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",78.400000
3,2016-2017,10,10,1.00,"3/3,42","6/6,100","0/0,0","0/0,0","1/1,32","0/0,0","0/0,0","0/0,0","0/0,0",75.800000
4,2016-2017,20,20,1.00,"4/4,42","11/11,100","1/1,0","3/3,0","1/1,32","0/0,0","0/0,0","0/0,0","0/0,0",65.000000
5,2017-2018,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
6,2017-2018,3,3,1.00,"0/0,0","3/3,90","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",90.000000
7,2017-2018,5,5,1.00,"2/2,88","3/3,90","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",89.200000
8,2017-2018,10,10,1.00,"6/6,83","3/3,90","1/1,39","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",80.700000
9,2017-2018,20,19,0.95,"10/10,86","6/6,93","2/2,69","0/0,0","1/1,0","0/1,0","0/0,0","0/0,0","0/0,0",77.800000
10,2018-2019,1,1,1.00,"1/1,55","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",55.000000
11,2018-2019,3,3,1.00,"1/1,55","0/0,0","1/1,0","1/1,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",18.333333
12,2018-2019,5,5,1.00,"1/1,55","2/2,97","1/1,0","1/1,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",49.800000
13,2018-2019,10,10,1.00,"3/3,72","3/3,98","2/2,0","1/1,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",51.000000
14,2018-2019,20,20,1.00,"4/4,73","8/8,96","2/2,0","2/2,0","0/0,0","0/0,0","1/1,0","1/1,0","2/2,0",53.000000
15,2019-2020,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
16,2019-2020,3,3,1.00,"1/1,69","2/2,97","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",87.666667
17,2019-2020,5,5,1.00,"2/2,53","2/2,97","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",60.000000
18,2019-2020,10,10,1.00,"4/4,61","5/5,98","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",73.400000
19,2019-2020,20,20,1.00,"10/10,66","8/8,99","0/0,0","0/0,0","1/1,0","0/0,0","0/0,0","1/1,0","0/0,0",72.600000

### Use 'Top 12 Forecast Probability' and then select the top 4 highest probability.

In [11]:
Accuracy(master_df,forecast_df)

,season,top_n,success,Hit rate,18,17,19,16,13,14,10,12,20,performance
0,2016-2017,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
1,2016-2017,3,3,1.00,"1/1,41","2/2,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",80.333333
2,2016-2017,5,5,1.00,"2/2,41","3/3,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",76.400000
3,2016-2017,10,10,1.00,"3/3,36","6/6,99","0/0,0","0/0,0","1/1,25","0/0,0","0/0,0","0/0,0","0/0,0",72.700000
4,2016-2017,20,20,1.00,"4/4,36","11/11,99","1/1,19","3/3,5","1/1,25","0/0,0","0/0,0","0/0,0","0/0,0",64.600000
5,2017-2018,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
6,2017-2018,3,3,1.00,"0/0,0","3/3,88","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",88.000000
7,2017-2018,5,5,1.00,"2/2,88","3/3,88","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",88.000000
8,2017-2018,10,10,1.00,"6/6,82","3/3,88","1/1,35","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",79.100000
9,2017-2018,20,19,0.95,"10/10,84","6/6,92","2/2,67","0/0,0","1/1,16","0/1,0","0/0,0","0/0,0","0/0,0",77.100000
10,2018-2019,1,1,1.00,"1/1,51","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",51.000000
11,2018-2019,3,3,1.00,"1/1,51","0/0,0","1/1,0","1/1,28","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",26.333333
12,2018-2019,5,5,1.00,"1/1,51","2/2,94","1/1,0","1/1,28","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",53.400000
13,2018-2019,10,10,1.00,"3/3,67","3/3,94","2/2,16","1/1,28","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",54.300000
14,2018-2019,20,20,1.00,"4/4,66","8/8,91","2/2,16","2/2,14","0/0,0","0/0,0","1/1,35","1/1,0","2/2,0",54.350000
15,2019-2020,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
16,2019-2020,3,3,1.00,"1/1,58","2/2,92","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",80.666667
17,2019-2020,5,5,1.00,"2/2,45","2/2,92","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",54.800000
18,2019-2020,10,10,1.00,"4/4,55","5/5,95","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",69.500000
19,2019-2020,20,20,1.00,"10/10,61","8/8,96","0/0,0","0/0,0","1/1,0","0/0,0","0/0,0","1/1,0","0/0,0",68.900000

### Use 'Top 12 Forecast Probability' and then select the top 5 highest probability.

In [15]:
Accuracy(master_df,forecast_df)

,season,top_n,success,Hit rate,18,17,19,16,13,14,10,12,20,performance
0,2016-2017,1,1,1.00,"0/0,0","1/1,98","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",98.000000
1,2016-2017,3,3,1.00,"1/1,39","2/2,99","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",79.000000
2,2016-2017,5,5,1.00,"2/2,38","3/3,99","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",74.600000
3,2016-2017,10,10,1.00,"3/3,33","6/6,98","0/0,0","0/0,0","1/1,24","0/0,0","0/0,0","0/0,0","0/0,0",71.100000
4,2016-2017,20,20,1.00,"4/4,34","11/11,98","1/1,16","3/3,5","1/1,24","0/0,0","0/0,0","0/0,0","0/0,0",63.450000
5,2017-2018,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
6,2017-2018,3,3,1.00,"0/0,0","3/3,87","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",87.000000
7,2017-2018,5,5,1.00,"2/2,88","3/3,87","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",87.400000
8,2017-2018,10,10,1.00,"6/6,81","3/3,87","1/1,33","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",78.000000
9,2017-2018,20,19,0.95,"10/10,84","6/6,91","2/2,66","0/0,0","1/1,13","0/1,0","0/0,0","0/0,0","0/0,0",76.550000
10,2018-2019,1,1,1.00,"1/1,48","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",48.000000
11,2018-2019,3,3,1.00,"1/1,48","0/0,0","1/1,0","1/1,23","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",23.666667
12,2018-2019,5,5,1.00,"1/1,48","2/2,93","1/1,0","1/1,23","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",51.400000
13,2018-2019,10,10,1.00,"3/3,64","3/3,92","2/2,13","1/1,23","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",51.700000
14,2018-2019,20,20,1.00,"4/4,62","8/8,89","2/2,13","2/2,17","0/0,0","0/0,0","1/1,29","1/1,0","2/2,0",52.450000
15,2019-2020,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
16,2019-2020,3,3,1.00,"1/1,52","2/2,89","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",76.666667
17,2019-2020,5,5,1.00,"2/2,40","2/2,89","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",51.600000
18,2019-2020,10,10,1.00,"4/4,51","5/5,93","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",66.900000
19,2019-2020,20,20,1.00,"10/10,58","8/8,94","0/0,0","0/0,0","1/1,0","0/0,0","0/0,0","1/1,0","0/0,0",66.600000

### Use 'Top 12 Forecast Probability' and then select the top 6 highest probability.

In [17]:
Accuracy(master_df,forecast_df)

,season,top_n,success,Hit rate,18,17,19,16,13,14,10,12,20,performance
0,2016-2017,1,1,1.00,"0/0,0","1/1,95","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",95.000000
1,2016-2017,3,3,1.00,"1/1,38","2/2,97","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",77.333333
2,2016-2017,5,5,1.00,"2/2,37","3/3,98","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",73.600000
3,2016-2017,10,10,1.00,"3/3,31","6/6,97","0/0,0","0/0,0","1/1,23","0/0,0","0/0,0","0/0,0","0/0,0",69.800000
4,2016-2017,20,20,1.00,"4/4,32","11/11,98","1/1,14","3/3,8","1/1,23","0/0,0","0/0,0","0/0,0","0/0,0",63.350000
5,2017-2018,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
6,2017-2018,3,3,1.00,"0/0,0","3/3,87","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",87.000000
7,2017-2018,5,5,1.00,"2/2,88","3/3,87","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",87.400000
8,2017-2018,10,10,1.00,"6/6,81","3/3,87","1/1,33","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",78.000000
9,2017-2018,20,19,0.95,"10/10,83","6/6,91","2/2,66","0/0,0","1/1,11","0/1,0","0/0,0","0/0,0","0/0,0",75.950000
10,2018-2019,1,1,1.00,"1/1,48","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",48.000000
11,2018-2019,3,3,1.00,"1/1,48","0/0,0","1/1,0","1/1,19","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",22.333333
12,2018-2019,5,5,1.00,"1/1,48","2/2,93","1/1,0","1/1,19","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",50.600000
13,2018-2019,10,10,1.00,"3/3,63","3/3,91","2/2,12","1/1,19","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",50.500000
14,2018-2019,20,20,1.00,"4/4,60","8/8,87","2/2,12","2/2,15","0/0,0","0/0,0","1/1,26","1/1,0","2/2,0",50.800000
15,2019-2020,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
16,2019-2020,3,3,1.00,"1/1,51","2/2,88","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",75.666667
17,2019-2020,5,5,1.00,"2/2,39","2/2,88","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,9","0/0,0",52.600000
18,2019-2020,10,10,1.00,"4/4,50","5/5,92","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,9","0/0,0",66.900000
19,2019-2020,20,20,1.00,"10/10,57","8/8,93","0/0,0","0/0,0","1/1,0","0/0,0","0/0,0","1/1,9","0/0,0",66.150000

### Use 'Top 12 Forecast Probability' and then select all of them.

In [19]:
Accuracy(master_df,forecast_df)

,season,top_n,success,Hit rate,18,17,19,16,13,14,10,12,20,performance
0,2016-2017,1,1,1.00,"0/0,0","1/1,91","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",91.000000
1,2016-2017,3,3,1.00,"1/1,38","2/2,95","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",76.000000
2,2016-2017,5,5,1.00,"2/2,36","3/3,97","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",72.600000
3,2016-2017,10,10,1.00,"3/3,30","6/6,96","0/0,0","0/0,0","1/1,23","0/0,0","0/0,0","0/0,0","0/0,0",68.900000
4,2016-2017,20,20,1.00,"4/4,31","11/11,97","1/1,12","3/3,7","1/1,23","0/0,0","0/0,0","0/0,0","0/0,0",62.350000
5,2017-2018,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
6,2017-2018,3,3,1.00,"0/0,0","3/3,86","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",86.000000
7,2017-2018,5,5,1.00,"2/2,88","3/3,86","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",86.800000
8,2017-2018,10,10,1.00,"6/6,81","3/3,86","1/1,32","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",77.600000
9,2017-2018,20,19,0.95,"10/10,83","6/6,90","2/2,66","0/0,0","1/1,9","0/1,0","0/0,0","0/0,0","0/0,0",75.550000
10,2018-2019,1,1,1.00,"1/1,47","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",47.000000
11,2018-2019,3,3,1.00,"1/1,47","0/0,0","1/1,9","1/1,17","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",24.333333
12,2018-2019,5,5,1.00,"1/1,47","2/2,93","1/1,9","1/1,17","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",51.800000
13,2018-2019,10,10,1.00,"3/3,62","3/3,90","2/2,15","1/1,17","0/0,0","0/0,0","0/0,0","1/1,0","0/0,0",50.300000
14,2018-2019,20,20,1.00,"4/4,59","8/8,86","2/2,15","2/2,13","0/0,0","0/0,0","1/1,25","1/1,0","2/2,1",50.350000
15,2019-2020,1,1,1.00,"0/0,0","1/1,100","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",100.000000
16,2019-2020,3,3,1.00,"1/1,49","2/2,86","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0",73.666667
17,2019-2020,5,5,1.00,"2/2,37","2/2,86","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,7","0/0,0",50.600000
18,2019-2020,10,10,1.00,"4/4,49","5/5,90","0/0,0","0/0,0","0/0,0","0/0,0","0/0,0","1/1,7","0/0,0",65.300000
19,2019-2020,20,20,1.00,"10/10,56","8/8,92","0/0,0","0/0,0","1/1,11","0/0,0","0/0,0","1/1,7","0/0,0",65.700000